version: '3'
services:
  app:
    image: armadik/app:dev
    build:
      context: app
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic my-topic-1 --replication-factor 1 --partitions 1
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

  click_server:
    image: yandex/clickhouse-server:21.3
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
    ports:
      - "8123:8123"
